[IV-23-24] Objetivo 3
spmanolo/calidad-aire pull request #17
Opened 2023-11-17 12:16 UTC by spmanolo

2023-11-17 13:03 UTC, spmanolo commented
@JJ Listo para revisión.

2023-11-17 15:50 UTC, carlosservi commented
Buenas compañero, me ha tocado ser revisor de tu PR, he estado revisando tu trabajo y veo que tiene lógica ya que vas a usar todo del estándar del Bun, pero veo que falta información, como por ejemplo, que criterios has usado para determinar las herramientas que utilizar. Además veo el readme muy escueto, pienso que deberías explicar mejor en el readme las decisiones tomadas, enlazar los ficheros, y explicar un poco como usarlo. Espero haberte ayudado. Un saludo

2023-11-20 09:55 UTC, spmanolo commented
@carlosservi Gracias por tu revisión! He hecho algunos cambios, échale un vistazo cuando puedas y me dices :smile:

2023-11-20 14:26 UTC, carlosservi approved these changes

2023-11-20 15:29 UTC, spmanolo commented
@JJ Listo 😄

2023-11-20 17:09 UTC, JJ requested changes
Por favor, recuerda que el objetivo aquí no es sólo que elijáis uno, sino que examinéis el panorama que hay. Aunque has presentado una buena cantidad de runtimes, ni has presentado los gestores de dependencias ni los de tareas. Es cierto que una vez elegido bun ya no queda mucho más remedio, pero presentar al menos las alternativas sin tener que examinarlas porque no hace falta sería conveniente; también puedes usar un gestor de tareas genérico como Make (u otros, hay varios por el estilo); el que tu criterio principal sea que esté todo integrado no quiere decir que no intentes ver y presentar otros que evidentemente no van a superar ese criterio, pero cuyo conocimiento te puede ser útil para otro proyecto que no use JavaScript.

2023-11-20 17:10 UTC, JJ commented
Y gracias a @carlosservi por la colaboración.

2023-11-20 19:39 UTC, JJ approved these changes
Sólo incluir Gulp sería razón suficiente para no pasar el objetivo, pero es ya un poco tarde, así que  confío en que lo elimines, mirando antes si está obsoleto (y quizás alguna alternativa) antes de fusionar la rama.

2023-11-20 19:39 UTC, JJ commented on docs/gestor_de_dependencias.md
> +#### YARN
No son acrónimos, no lo pongas todo en mayúscula.

2023-11-20 19:39 UTC, JJ commented on docs/task_runner.md
> +#### GULP
De veras, no volváis a poner gulp. Está irremediablemente obsoleto.

2023-11-20 19:52 UTC, spmanolo commented
Vale, arreglaré eso antes de fusionar, gracias! :+1:

2023-11-20 20:05 UTC, spmanolo commented on docs/task_runner.md
> +#### GULP
Solucionado en a096ea93ef367ff00219a9081d03f5a7d192badf

2023-11-20 20:05 UTC, spmanolo commented on docs/gestor_de_dependencias.md
> +#### YARN
Solucionado en ffec4df86e4b1476b40ad888b3ce1e7214afaeac

2023-11-20 20:06 UTC, merged