[IV-23-24] Objetivo 4
spmanolo/calidad-aire pull request #22
Opened 2023-11-24 12:31 UTC by spmanolo

2023-11-28 17:39 UTC, puchy22 commented
Este commit 284443058b47740e48c5670bfb3c1ca011496c99 no creo que siga las mejores prácticas ya que cierra un issue pero soluciona dos problemas el de la selección y mejorar el formato de los archivos. Intenta para las próximas ocasiones abrir un issue para cada problema que te encuentres y no meter la solución en un commit que no corresponde ya que tampoco se indica en el título del mismo.

2023-11-28 18:12 UTC, puchy22 requested changes

2023-11-28 18:12 UTC, puchy22 commented on test/calidad_del_aire.test.ts
> +        console.log("media de mediciones: ", mediaMedidas);
El problema principal que veo en este test es que no es un test que valide tu lógica de negocio en ningún memento, solo muestras por consola la media de las medidas. Si tu lógica de negocio es calcular la media de las mediciones de contaminación de un día en una zona específica deberás comprobar que tu programa calcula de manera correcta esta media, es decir; en tus datos de prueba tienes el resultado real de esta media por cada zona y lo comparas con la salida de tu programa, si no el test no está comprobando la lógica de negocio solo que los vectores tienen el tamaño correcto, pero hay que verificar el valor de estos vectores.

2023-11-28 18:12 UTC, puchy22 commented on src/calidad_del_aire.ts
> +  public extraerMediciones(
Esto es más bien una recomendación y es si no has pensado en usar alguna dependencia extra para leer .csv en typescript como https://www.papaparse.com/ o https://github.com/mafintosh/csv-parser. Puede que te facilitase un poco el trabajo en este método.

2023-11-28 19:25 UTC, spmanolo commented on test/calidad_del_aire.test.ts
> +      ruta: "https://www.juntadeandalucia.es/medioambiente/atmosfera/informes_siva/cuantitativo/2023/GR_20231124.csv",
La añadí para intentar hacer pruebas descargando el fichero desde la web pero esa parte aún no la he implementado, lo que compruebo es que una vez descargado el fichero se calcule la media.

2023-11-28 19:29 UTC, spmanolo commented on src/calidad_del_aire.ts
> +  public extraerMediciones(
Estuve mirando la dependencia `csv-parser`, pero cuando vi que leyendo el fichero con `fs` se podía extraer la información de forma aceptable, decidí obviarlo. En un futuro igual se podría mirar para optimizar un poco el código. Gracias por la recomendación :smile:

2023-11-28 19:31 UTC, spmanolo commented on test/calidad_del_aire.test.ts
> +        console.log("media de mediciones: ", mediaMedidas);
Tienes razón, no sabía muy bien como comprobar esa parte y solo compruebo el tamaño del resultado. En cuanto pueda lo arreglo, gracias!!

2023-11-30 18:41 UTC, spmanolo commented on docs/test_runner.md
> +Para TypeScript existen varios frameworks para escribir tests bastante conocidos. Todos los que comento contienen bibliotecas de aserciones que siguen el estilo BDD y tienen su propio CLI para ejecut
Resuelto en 0f8af61d80be6a049ae199c2a17392e5a4ff2e32

2023-11-30 18:41 UTC, spmanolo commented on test/calidad_del_aire.test.ts
> +        console.log("media de mediciones: ", mediaMedidas);
Resuelto en 10db2fde2f912e8ba424a94a7fc14abc06787ebd

2023-12-02 10:31 UTC, spmanolo commented
@puchy22 Cuando puedas échale un vistazo a los cambios y me dices :smile:

2023-12-04 15:48 UTC, puchy22 approved these changes
Lo veo bastante bien :+1:. La única recomendación que te podría hacer más es que hay comentarios en el código, como en los test, que no aportan demasiado y se podrían omitir haciendo el código más limpio. Por el resto buen trabajo :100:.

2023-12-04 16:32 UTC, spmanolo commented
> Lo veo bastante bien 👍. La única recomendación que te podría hacer más es que hay comentarios en el código, como en los test, que no aportan demasiado y se podrían omitir haciendo el código más limpio. Por el resto buen trabajo 💯.

Lo acabo de arreglar. Muchas gracias por la revisión!! :)

2023-12-04 16:35 UTC, JJ commented
Me temo que salgo ahora mismo de puente. Me pongo cuando vuelva; mientras tanto puedes empezar el siguiente si te apetece

2023-12-04 16:39 UTC, spmanolo commented
> Me temo que salgo ahora mismo de puente. Me pongo cuando vuelva; mientras tanto puedes empezar el siguiente si te apetece

Genial. Que vaya bien!!

2023-12-11 07:29 UTC, JJ commented
> * [x]   ¿Hay un camino claro que permita ir desde el código hasta la historia de
>       usuario que desarrolla, pasando por el mensaje de commit y el issue
>       correspondiente?
> 
>     * [x]   ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
>       esté desarrollando?
> 
>     * [x]   ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
>       este objetivo?
> 
>     * [x]   ¿En este producto mínimamente viable se han priorizado unas clases,
>       módulos o paquetes más fundamentales frente a otros, movidos a otro
>       PMV/Hito?
> 
>     * [x]  ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
>       delante?
>       Estoy leyendo

Pues entonces no marques... 

> 
>     * [x]  ¿Se han documentado las elecciones de biblioteca de aserciones y del
>       de _test runner_?
> 
>     * [x]  ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
>       test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
>       `unittest` como _test runner_ y `pytest` como biblioteca de aserciones?
> 
>     * [x]  ¿Esa documentación incluye criterios de aceptación y también criterios de
>       búsqueda para las diferentes opciones?
> 
>     * [x]   ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
>       se ha documentado cómo se ha hecho?
> 
>     * [x]   ¿Se describe claramente en el PMV los tests que hay que pasar para que se
>       considere viable?
> 
>     * [x]  ¿Se han testeado también las excepciones?

Por favor, no marquéis las cosas al buen tuntún.

2023-12-11 07:31 UTC, JJ commented on docs/test_runner.md
> +### Chai
Por favor, enlazad las bibliotecas que estéis comentando.

2023-12-11 07:33 UTC, JJ commented on docs/test_runner.md
> +
No estás comentando la biblioteca de aserciones que efectivamente has elegido. Aunque elijas `bun` como test runner, la elección de biblioteca de aserciones e incluso de biblioteca de test puede ser otra perfectamente. Haber optado por `bun:test` no era obvio, ni tampoco lo has justificado.

2023-12-11 12:45 UTC, spmanolo commented on docs/test_runner.md
> +### Chai
Solucionado en 4fc32b9cae740bc4f5bdec36292bcf8000caf817

2023-12-11 12:46 UTC, spmanolo commented on docs/test_runner.md
> +
Solucionado en 5851dd555e0bd2ee6dd95db05b9475e153b1b787

2023-12-11 13:15 UTC, JJ requested changes
El problema principal, aparte de lo comentado, es que no "veo" la historia de usuario testeada: #5 ¿está pudiendo ver si alguno de los alérgenos está subiendo o bajando?  Como pone [en los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-4.md#sobre-la-programaci%C3%B3n):

> Hay que comprobar que se cumple lo que pide la lógica de negocio. Si se pide que algo sea mínimo, o mejor, u óptimo, hay que comprobar que efectivamente el resultado es el mínimo, o mejor que otros, u óptimo; hay que tener una función que compruebe la "bondad" o lo que sea de la solución y mostrar que efectivamente es la mejor según ese criterio.

2023-12-11 13:15 UTC, JJ commented on src/calidad_del_aire.ts
> +          Number(elementos_linea[5]),
DRY, no repitas código.

2023-12-11 19:51 UTC, spmanolo commented on docs/test_runner.md
> +- Como criterio principal voy a establecer la facilidad de uso y la velocidad de ejecución. Con facilidad de uso también me refiero a la integración con el runtime, así que si el framework ya viene i
¿A qué te refieres exactamente? El criterio principal es que venga integrado con el runtime por facilidad de uso y siguiendo esos criterios finalmente me he decantado por `bun:test`. Creo que igual no lo he expresado bien, lo he arreglado en 7bb98310b6580b85e17cbf25046909a0931a9dd6

2023-12-11 21:54 UTC, spmanolo commented on src/calidad_del_aire.ts
> +          Number(elementos_linea[5]),
Solucionado en 9704235

2023-12-12 06:26 UTC, JJ commented on docs/test_runner.md
> +- Como criterio principal voy a establecer la facilidad de uso y la velocidad de ejecución. Con facilidad de uso también me refiero a la integración con el runtime, así que si el framework ya viene i
¿Qué velocidad de ejecución tiene `bun:test` con respecto a sus competidores?

2023-12-12 06:40 UTC, JJ requested changes
Me temo que sigues teniendo el mismo problema: no estás testeando la historia de usuario. Esta dice:

> que me permita saber la *calidad del aire* en la *zona en la que me encuentro* de una forma *lo más precisa posible*, sin fallos y fiable.

1. Estás hablando de "calidad del aire" para una persona con alergia. Si mal no recuerdo, son las partículas las que afectan a la persona con alergia, pero en todo caso debería haber una función de alto nivel que fuera explícitamente para personas con alergia.
2. No hay ninguna función que trabaje con ninguna zona que no sean las que ya tienen las estaciones. En 3bc50f2 "añades lógica de negocio para la media de mediciones", pero sólo lo haces para las zonas donde hay medidor.
3. De la misma forma, se pide *lo más precisa posible", pero hallas medias de todo el histórico, aparentemente. No sé hasta qué punto eso será preciso.
4. Hablas de "sin fallos", y durante el primer y segundo objetivo (0 y 1) estuvimos hablando de que algunos medidores tenían problemas y que una de las cosas fundamentales era detectar esos problemas. Tampoco lo estás detectando, ni parece que haya entre los ficheros de test ninguno que contenga errores en las mediciones. Aunque entiendo que este último es más complicado, al menos los otros tres deberías hacer un esfuerzo por hacerlos.

Al final, en desarrollo ágil se trata de hacer una aplicación que satisfaga al cliente. En este objetivo es donde se lleva a cabo la lógica de negocio para ello, y donde efectivamente se deben encontrar funciones, y test, que reflejen de la mejor forma posible las historias de usuario. Intenta, por favor, verlo desde ese punto de vista.

2023-12-12 06:40 UTC, JJ commented on test/calidad_del_aire.test.ts
> +          calidadDelAire.getMedicionesContaminacion();
Esta función la estás usando solo en los tests. ¿Estás seguro de que es necesaria? Recuerda que el API de una clase debe incluir sólo lo que se use desde otras clases o pida la HU

2023-12-12 06:40 UTC, JJ commented on test/calidad_del_aire.test.ts
> +        console.log("zona: ", calidadDelAire.getZona());
Eliminad las impresiones para depurar antes de enviar, por favor.

2023-12-12 07:17 UTC, spmanolo commented
> Me temo que sigues teniendo el mismo problema: no estás testeando la historia de usuario. Esta dice:
> 
> > que me permita saber la _calidad del aire_ en la _zona en la que me encuentro_ de una forma _lo más precisa posible_, sin fallos y fiable.
> 
> 1. Estás hablando de "calidad del aire" para una persona con alergia. Si mal no recuerdo, son las partículas las que afectan a la persona con alergia, pero en todo caso debería haber una función de alto nivel que fuera explícitamente para personas con alergia.
> 2. No hay ninguna función que trabaje con ninguna zona que no sean las que ya tienen las estaciones. En [3bc50f2](https://github.com/spmanolo/calidad-aire/commit/3bc50f2e5b85b5f1c519b9b56b2c2d0f5cec07b1) "añades lógica de negocio para la media de mediciones", pero sólo lo haces para las zonas donde hay medidor.
> 3. De la misma forma, se pide *lo más precisa posible", pero hallas medias de todo el histórico, aparentemente. No sé hasta qué punto eso será preciso.
> 4. Hablas de "sin fallos", y durante el primer y segundo objetivo (0 y 1) estuvimos hablando de que algunos medidores tenían problemas y que una de las cosas fundamentales era detectar esos problemas. Tampoco lo estás detectando, ni parece que haya entre los ficheros de test ninguno que contenga errores en las mediciones. Aunque entiendo que este último es más complicado, al menos los otros tres deberías hacer un esfuerzo por hacerlos.
> 
> Al final, en desarrollo ágil se trata de hacer una aplicación que satisfaga al cliente. En este objetivo es donde se lleva a cabo la lógica de negocio para ello, y donde efectivamente se deben encontrar funciones, y test, que reflejen de la mejor forma posible las historias de usuario. Intenta, por favor, verlo desde ese punto de vista.

Si, aún estoy en ello pero muchas gracias por las aclaraciones!! Siempre son útiles :)

2023-12-12 18:29 UTC, spmanolo commented
> 2\. No hay ninguna función que trabaje con ninguna zona que no sean las que ya tienen las estaciones. En [3bc50f2](https://github.com/spmanolo/calidad-aire/commit/3bc50f2e5b85b5f1c519b9b56b2c2d0f5cec07b1) "añades lógica de negocio para la media de mediciones", pero sólo lo haces para las zonas donde hay medidor.

Con esto te refieres a que si el usuario establece una zona específica, ¿se deberia devolver los datos de la estación más cercana a esa zona? Es que en un principio puse la zona como una estación específica para no complicarme tanto las cosas y centrarme en lo esencial.

2023-12-12 18:59 UTC, spmanolo commented on test/calidad_del_aire.test.ts
> +        console.log("zona: ", calidadDelAire.getZona());
Solucionado en 8fb97099b9891592c4bc2ca9eb3c560df53dea28

2023-12-12 18:59 UTC, spmanolo commented on test/calidad_del_aire.test.ts
> +          calidadDelAire.getMedicionesContaminacion();
Solucionado en 9fc542516bc85753d6d36828473da488c964fc51

2023-12-12 19:06 UTC, spmanolo commented on docs/test_runner.md
> +- Como criterio principal voy a establecer la facilidad de uso y la velocidad de ejecución. Con facilidad de uso también me refiero a la integración con el runtime, así que si el framework ya viene i
Solucionado en f0d4cf9b86dbc87f27fe233ccc8a98484c78e4ca

2023-12-13 06:28 UTC, JJ commented
> > 2. No hay ninguna función que trabaje con ninguna zona que no sean las que ya tienen las estaciones. En [3bc50f2](https://github.com/spmanolo/calidad-aire/commit/3bc50f2e5b85b5f1c519b9b56b2c2d0f5cec07b1) "añades lógica de negocio para la media de mediciones", pero sólo lo haces para las zonas donde hay medidor.
> 
> Con esto te refieres a que si el usuario establece una zona específica, ¿se deberia devolver los datos de la estación más cercana a esa zona? Es que en un principio puse la zona como una estación específica para no complicarme tanto las cosas y centrarme en lo esencial.

La solución tienes que decidirla tú, creando un issue. Lo que *no* dice la historia de usuario es "estoy al lado de una estación, dame el PM que has leído del fichero" que has estado testeando. En desarrollo ágil *siempre* tienes que tener en cuenta lo que el usuario busca.

2023-12-15 21:08 UTC, spmanolo commented
@JJ Listo para revisión

2023-12-16 09:01 UTC, JJ requested changes
Me perdonarás que no lo haya revisado completo, pero es que tampoco quiero apabullarte. Hay una serie de temas que tienes que considerar, te agradecería que le echaras un vistazo.
Recuerda también que has marcado:
>  ¿Se han testeado también las excepciones?
En el código revisado hay muchas situaciones en las que podrías considerar lanzar una excepción, y por supuesto testearla. Y las excepciones tienen también que diseñarse, tener su tipo, para que se pueda identificar dónde ha sucedido el error.

2023-12-16 14:17 UTC, spmanolo commented on package.json
> +    "typescript": "5.0.0"
Eso se creó cuando inicié el proyecto con Bun, lo añadió como `peerDependencies`. Le quité el `^` para que no se actualice la versión de `TypeScript` en el proyecto y siempre se use la misma versión, por si en una nueva versión cambia alguna funcionalidad y provoca problemas.

2023-12-17 08:38 UTC, JJ commented on package.json
> +    "typescript": "5.0.0"
¿Has probado a quitarlo a ver qué pasa?

2023-12-17 15:48 UTC, spmanolo commented on package.json
> +    "typescript": "5.0.0"
La verdad es que sigue funcionando todo igual :sweat_smile:

2023-12-17 16:53 UTC, spmanolo commented on package.json
> +    "typescript": "5.0.0"
Solucionado en [895f158](https://github.com/spmanolo/calidad-aire/pull/22/commits/895f158e8bb6f194ea27cd7765aef0cf10c8f521)

2023-12-17 17:08 UTC, spmanolo commented on src/datos_de_medicion.ts
> +  private leerArchivo(): void {
Solucionado en [9830307](https://github.com/spmanolo/calidad-aire/pull/22/commits/98303074e0fb584a8541d2e95b601774996471f3)

2023-12-17 17:09 UTC, spmanolo commented on src/datos_de_medicion.ts
> +      this.mediciones = fs.readFileSync(this.ruta, "utf8");
Solucionado en [9830307](https://github.com/spmanolo/calidad-aire/pull/22/commits/98303074e0fb584a8541d2e95b601774996471f3)

2023-12-17 17:09 UTC, spmanolo commented on src/datos_de_medicion.ts
> +  public getMediciones(): string | null {
Solucionado en [9830307](https://github.com/spmanolo/calidad-aire/pull/22/commits/98303074e0fb584a8541d2e95b601774996471f3)

2023-12-17 17:09 UTC, spmanolo commented on src/datos_de_medicion.ts
> +export class DatosDeMedicion {
Solucionado en [9830307](https://github.com/spmanolo/calidad-aire/pull/22/commits/98303074e0fb584a8541d2e95b601774996471f3)

2023-12-17 17:09 UTC, spmanolo commented on src/mediciones_de_contaminacion.ts
> +  private pm10: number;
Solucionado en [9830307](https://github.com/spmanolo/calidad-aire/pull/22/commits/98303074e0fb584a8541d2e95b601774996471f3)

2023-12-17 17:10 UTC, spmanolo commented on src/mediciones_de_contaminacion.ts
> +      ["pm10", this.pm10],
Solucionado en [9830307](https://github.com/spmanolo/calidad-aire/pull/22/commits/98303074e0fb584a8541d2e95b601774996471f3)

2023-12-17 17:10 UTC, spmanolo commented on src/mediciones_de_contaminacion.ts
> +    this.pm10 = mediciones[0];
Solucionado en [9830307](https://github.com/spmanolo/calidad-aire/pull/22/commits/98303074e0fb584a8541d2e95b601774996471f3)

2023-12-17 17:10 UTC, spmanolo commented on src/mediciones_de_contaminacion.ts
> +  constructor(mediciones: number[]) {
Solucionado en [9830307](https://github.com/spmanolo/calidad-aire/pull/22/commits/98303074e0fb584a8541d2e95b601774996471f3)

2023-12-17 17:11 UTC, spmanolo commented on src/particulas_del_aire.ts
> +    let infoMediciones: string | null = mediciones.getMediciones();
Solucionado en [9830307](https://github.com/spmanolo/calidad-aire/pull/22/commits/98303074e0fb584a8541d2e95b601774996471f3)

2023-12-17 17:13 UTC, JJ approved these changes
Creo que lo voy a dar por bueno, pero te agradecería que le dieras una vuelta a las cosas comentadas antes del siguiente (o después más adelante, ahora céntrate en sacar el objetivo 5)

2023-12-17 17:13 UTC, JJ commented on src/particulas_del_aire.ts
> +    this.ruta_archivo = ruta;
¿La ruta del archivo la vas a necesitar después de construir el objeto?

2023-12-17 17:13 UTC, JJ commented on src/particulas_del_aire.ts
> +        let medicion: MedicionDeContaminacion = {
¿Constante o variable?

2023-12-17 17:13 UTC, JJ commented on src/particulas_del_aire.ts
> +    if (this.mediciones.length == 0) {
¿Ves lo que pasa si no te aseguras que está inicializado una vez construido?

2023-12-17 17:16 UTC, spmanolo commented
> Creo que lo voy a dar por bueno, pero te agradecería que le dieras una vuelta a las cosas comentadas antes del siguiente (o después más adelante, ahora céntrate en sacar el objetivo 5)

Genial, le echaré un vistazo. Gracias!!

2023-12-17 17:17 UTC, merged