[IV-23-24] Objetivo 5
spmanolo/calidad-aire pull request #36
Opened 2023-12-27 18:27 UTC by spmanolo

2023-12-30 13:32 UTC, danieeeld2 reviewed
En general, buen trabajo. Solo tengo la sugerencia comentada abajo. Mucho ánimo con los objetivos y felices fiestas😄

2023-12-30 13:32 UTC, danieeeld2 commented on Dockerfile
> +COPY package.json ./ \
Aquí, si es posible, sería mejor copiar e instalar las dependencias en otro directorio, ya que, en el directorio donde se ejecutan los tests, el usuario no tiene privilegios de escritura. En mi caso, que usaba `Go`, me daba bastantes problemas estos y tenía que cargar en instalar las dependencias en `/app` y ya, después, cambiar a `/app/test` para ejecutar los tests.

2023-12-30 17:16 UTC, spmanolo commented on Dockerfile
> +COPY package.json ./ \
Solucionado en 745ff9f19116fdb39b2a7ef21829ac242caf32f6

2023-12-30 17:17 UTC, spmanolo commented
> En general, buen trabajo. Solo tengo la sugerencia comentada abajo. Mucho ánimo con los objetivos y felices fiestas😄

Igualmente y muchas gracias por la revisión!! :)

2023-12-30 17:18 UTC, spmanolo commented
@JJ Listo para revisión

2023-12-31 10:20 UTC, JJ requested changes
Salvo el error indicado (y posiblemente algún contenedor base de algún otro sistema operativo considerado, y quizás borrar cosas innecesarias del contenedor) estaría correcto. Un paso más y lo tienes.

2023-12-31 10:20 UTC, JJ commented on Dockerfile
> +RUN apt update && \
Una vez construido el contenedor, ¿necesitas curl y unzip?

2023-12-31 10:20 UTC, JJ commented on Dockerfile
> +    bun.lockb ./
Al fusionar los dos comandos en uno creo que hay un error. `COPY` tiene como sintaxis 

```
COPY filea fileb filec ... filex directorio
```

Por lo tanto, lo que estás haciendo aquí no es copiar un fichero a un directorio y otro fichero al mismo directorio. Sino fichero, directorio del anfitrión, otro fichero, a la imagen... `fileb` es aquí `.`

2023-12-31 11:21 UTC, spmanolo commented on Dockerfile
> +RUN apt update && \
Si, para instalar Bun, porque me daba errores por no tenerlos instalados

2023-12-31 11:29 UTC, JJ commented on Dockerfile
> +RUN apt update && \
Una vez instalado, ¿los necesitas?

2023-12-31 12:19 UTC, spmanolo commented on Dockerfile
> +RUN apt update && \
Ah, cierto

2023-12-31 13:57 UTC, spmanolo commented on Dockerfile
> +RUN apt update && \
Solucionado en [e03f0e7](https://github.com/spmanolo/calidad-aire/pull/36/commits/e03f0e772e567627f5c17a5dbc1258bfdf2cd4b2)

2023-12-31 13:57 UTC, spmanolo commented on Dockerfile
> +    bun.lockb ./
Solucionado en [e03f0e7](https://github.com/spmanolo/calidad-aire/pull/36/commits/e03f0e772e567627f5c17a5dbc1258bfdf2cd4b2)

2023-12-31 13:58 UTC, spmanolo commented
@JJ Listo. Para cuando puedas y perdón por las horas. Feliz año!!

2023-12-31 17:50 UTC, JJ approved these changes
:+1:  y feliz año también.

2024-01-08 16:46 UTC, merged