[IV-23-24] Objetivo 1
spmanolo/calidad-aire pull request #4
Opened 2023-09-23 10:25 UTC by spmanolo

**Sobre los milestones**
* [X] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [X] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [X] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [X] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [X] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [X] ¿Los milestones son graduales, o hay un salto grande entre ellos?
Son graduales y se deben seguir en orden para el correcto desarrollo.

* [X] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
Los primeros milestones son tareas internas por ahora.

* [X] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [X] ¿El milestone 0 es mínimo *y* viable?
* [] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

**Sobre las historias de usuario**
* [X] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [X] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [X] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [X] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?
Las historias de usuario representan un beneficio para el usuario y se relacionan con la lógica de negocio.

2023-09-25 12:43 UTC, JJ requested changes
Mirando los datos que mencionas, están en un formato más o menos aceptable, aunque evidentemente hay que procesarlo. En desarrollo ágil hay, sin embargo, que aprovechar las oportunidades, y lo que veo ahí  es que en algunos casos las casillas correspondientes están vacías o que tienen valores raros
![Captura de pantalla de 2023-09-25 14-42-33](https://github.com/spmanolo/calidad-aire/assets/500/b05a0870-18bc-4d20-8be1-cd05533ac7a4)
Así que ahí tienes problemas adicionales: rellenar las casillas que falten, ver qué valores son extraños (o qué procesamiento adicional necesitan estos valores) o ver si algún valor falta durante mucho tiempo, lo que indicaría una posible falla en el funcionamiento del sensor.

2023-09-25 12:43 UTC, JJ commented on docs/historias_usuario.md
> +**User journey**: el usuario accede a la aplicación, elige la zona en la que se encuentra y el día que desea comprobar y se le proporcionará la información de la media de contaminación en esa zona y
Cada tipo de usuario debería de tener su propio user journey.

2023-09-25 12:43 UTC, JJ commented on docs/historias_usuario.md
> +- **HU1-0** Como usuario, necesito saber la información de
Aparte de que debes repetir qué usuario es, no queda claro que esto incluya ninguna lógica de negocio. Por favor, explica el contexto que revele el verdadero problema: extraer la información, más que procesarla.

2023-09-25 12:43 UTC, JJ commented on docs/historias_usuario.md
> +### Como periodista de investigación, necesitaría conocer la información de la contaminación en un día y provincia concreto que me sirva para mi investigación sobre algún caso relacionado con la cali
Una vez más, explica claramente de qué se trata y cuál es el problema: información que hay que teclear a mano, o cortar o pegar, o lo que sea.

2023-09-25 12:43 UTC, JJ commented on docs/milestones.md
> +Se necesita obtener una media de los datos de contaminación obtenidos, que se tendrá que comparar con el umbral de contaminación para saber el nivel de gravedad.
Lo que haya que obtener o no es algo que quien desarrolle tiene que decir. Lo que sí hay que hacer es implementar la lógica de negocio.

2023-09-25 12:49 UTC, JJ commented
Estoy viendo los números esos tan altos y se deben a que LibreOffice simplemente interpreta el `.` como punto de miles, no de decimales. En el fichero se ve bien, pero en todo caso puede que haya valores excesivos reales o erróneos, y que como comentamos en clase se puedan hacer predicciones simples tipo "va a ir a peor" o "va a mejorar"

2023-09-27 20:41 UTC, spmanolo commented
@JJ Listo para revisión. He intentado plasmar la lógica de negocio tanto en las historias de usuario como en los milestones tal y como yo la he entendido.

2023-09-28 11:00 UTC, JJ commented on docs/milestones.md
> +La aplicación debe procesar los datos que introduce el usuario como son la zona en la que se encuentra y el día que desea comprobar. Se necesita obtener una media de los datos de contaminación obteni
Creo que hemos quedado que el problema principal no es responder al usuario, sino tomar los datos del fichero y extraerlos correctamente, teniendo en cuenta si faltan datos o si hay errores. Por favor, refléjalo aquí.

2023-09-28 11:01 UTC, JJ commented on docs/historias_usuario.md
> +**User journey**: el usuario accede a la aplicación, elige la zona en la que se encuentra y el día actual y se le proporcionará la información de la media de contaminación en esa zona en el día actua
Los user journey deben ir en un fichero diferente, del *user journey* se extrae la historia de usuario.

2023-09-28 11:12 UTC, JJ commented on docs/historias_usuario.md
> +### Como una persona con alergia, me encuentro en una ciudad grande y no se si salir a la calle hoy me supondría un problema debido a la mala calidad del aire, ya que un día salí a la calle y debido
¿Con qué precisión necesita saberla? ¿Qué ocurre si hay un indicador específico de calidad del aire que no se publica? ¿Qué ocurre si el sensor ha dejado de funcionar?

2023-09-28 16:35 UTC, spmanolo commented on docs/milestones.md
> +Habrá que plasmar en código el modelo del problema que se describe en las historias de usuario.
¿Qué debería hacerlo viable? ¿Quizá que el diseño del problema no tenga fallos o algo así?

2023-09-28 17:22 UTC, spmanolo commented on docs/milestones.md
> +La aplicación debe procesar los datos que introduce el usuario como son la zona en la que se encuentra y el día que desea comprobar. Se necesita obtener una media de los datos de contaminación obteni
Entiendo que la lógica de negocio abarca tanto la entrada de datos como el procesamiento de esos datos junto con datos internos (en mi caso los datos de la API) y la posterior entrega de un resultado no? Por eso he visto necesario explicar que se va a recibir una entrada del usuario y éste va a recibir una respuesta. Voy a modificarlo para incluir que el procesamiento de los datos tiene que ser correcto y sin fallos y en el caso de que los haya, corregirlos mediante predicciones.

2023-09-28 17:42 UTC, JJ commented on docs/milestones.md
> +Habrá que plasmar en código el modelo del problema que se describe en las historias de usuario.
Eso es precisamente lo que tú tienes que poner aquí. ¿Cómo sabes que un modelo es viable?

2023-09-28 17:43 UTC, JJ commented on docs/milestones.md
> +La aplicación debe procesar los datos que introduce el usuario como son la zona en la que se encuentra y el día que desea comprobar. Se necesita obtener una media de los datos de contaminación obteni
No es un API, es un fichero que te descargas. Si fuera un API no habría pasado del objetivo 0.

2023-09-28 18:34 UTC, spmanolo commented on docs/milestones.md
> +Habrá que plasmar en código el modelo del problema que se describe en las historias de usuario.
Entiendo que es viable si cumple con los requisitos que se describen en la historia de usuario no?

2023-09-29 05:39 UTC, JJ commented on docs/milestones.md
> +Habrá que plasmar en código el modelo del problema que se describe en las historias de usuario.
El criterio de viabilidad, si no es obvio, tiene que formar parte de la descripción del milestone. Cuando lo incluyas, te comento.

2023-09-29 19:04 UTC, spmanolo commented
@JJ Listo para revisión

2023-09-30 07:41 UTC, JJ approved these changes
Gracias por tomarte el trabajo de acabar esto :+1:

2023-09-30 09:43 UTC, merged