[IV-23-24] Objetivo 2
spmanolo/calidad-aire pull request #8
Opened 2023-10-06 12:06 UTC by Enaraque

2023-10-06 12:11 UTC, spmanolo commented
:+1:  Listo. Te he asignado el M0!

2023-10-18 21:34 UTC, Enaraque commented
Hola @spmanolo, acabo de crear la estructura que comentamos en #9. Cuando puedas échales un vistazo y coméntame cualquier duda que tengas así como cualquier cambio que veas oportuno. También, asígnale el milestone correspondiente a cada issue. Un saludo! 😺

2023-10-19 19:20 UTC, spmanolo approved these changes
Buen trabajo! Yo lo veo todo bien estructurado y organizado, cumple con los requisitos del M0 y obtenemos un pmv que sirve para avanzar en el proyecto así que genial :+1:

2023-10-19 19:20 UTC, spmanolo commented on src/medicionesDeContaminacion.ts
> +    private so2: number;
El modularizar las mediciones está muy bien para almacenar todos los tipos de alérgenos

2023-10-19 19:20 UTC, spmanolo commented on src/zona.ts
> +
Los atributos de la clase Zona se corresponden con los datos de la ubicación que proporciona la Junta así que perfecto.

2023-10-19 19:20 UTC, spmanolo commented on src/calidadDelAire.ts
La clase principal está perfectamente estructurada, yo lo veo genial.

2023-10-20 09:45 UTC, spmanolo commented
Te acabo de asignar el milestone corresponidiente a cada issue que faltaba por hacer :smile:

2023-10-20 11:08 UTC, spmanolo commented
* [X] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [X] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [X] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [X] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [X] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [X] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [X] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [X] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2023-10-20 11:08 UTC, spmanolo commented
@JJ Listo para revisión.

2023-10-20 11:46 UTC, JJ requested changes
Es importante que tengáis en cuenta las mejores prácticas en nombres de ficheros. Por lo demás, creo que habéis seguido la metodología correctamente.

2023-10-20 11:46 UTC, JJ commented on src/calidadDelAire.ts
> +import { Zona } from "./zona";
Las buenas prácticas en cualquier repo no aconsejan que se usen mayúsculas en los nombres de ficheros (porque hay sistemas de ficheros, como el del Mac, que no lo distinguen)

2023-10-20 11:46 UTC, JJ commented on src/zona.ts
> +    private privincia: string;
¿Una privincia es una provincia a la que le va la priva?

2023-10-20 11:46 UTC, JJ commented on src/zona.ts
> +        this.privincia = provincia;
Esto ya duele los ojos un poquito...

2023-10-20 12:08 UTC, Enaraque commented
@JJ He cambiado el nombre de los ficheros a unos mas adecuados, también he arreglado el typo de 'privincia'.
Listo para revisión

2023-10-20 12:17 UTC, JJ approved these changes
👍 Gracias por reaccionar tan rápido.

2023-10-30 18:06 UTC, merged